### ISSUE TITLE
Update include statements to newer syntax

### ISSUE THREAD

**Issue by deadbok** [deadbok/ansible-librenms#5]
Ansible on Debian stretch has the following warning:

```
[DEPRECATION WARNING]: Specifying include variables at the top-level of the 
task is deprecated. Please see:

http://docs.ansible.com/ansible/playbooks_roles.html#task-include-files-and-
encouraging-reuse

 for currently supported syntax regarding included files and
 variables.
This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

Description of the new syntax is here:

[http://docs.ansible.com/ansible/latest/playbooks_reuse.html](http://docs.ansible.com/ansible/latest/playbooks_reuse.html)

**Comment by deadbok** [comment]
The new syntax is supported in Ansible version 2.4+ according to this [http://docs.ansible.com/ansible/latest/playbooks_reuse_includes.html](http://docs.ansible.com/ansible/latest/playbooks_reuse_includes.html).

Debian Jessie install version 1.7.2:

```
vagrant@jessie:~$ ansible --version
ansible 1.7.2
```

@moozer Do you need Jessie support?

**Comment by moozer** [comment]
It is the vars section of test.yml.

I have replaced it with stuff in group_vars/all.yml
